services:
  - type: web
    name: jus-provas-app
    env: docker
    region: ohio
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: "*"
      - key: VITE_API_BASE
        value: /api
      - key: ACTIVE_PROVIDER
        value: offline
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
